image: maven:3.6.0-jdk-11

cache:
  paths:
    - .m2
  key: "$CI_BUILD_REF_NAME"

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"

stages:
  - build
  - unit-test
  - integration-test
  - deploy

build:
  stage: build
  script:
    - mvn -B -s .m2/settings.xml compile

unit-test:
  stage: unit-test
  script:
    - mvn -B -s .m2/settings.xml test

integration-test:
  stage: integration-test
  script:
    - mvn -B -s .m2/settings.xml integration-test -DskipTests

deploy:
  stage: deploy
  script:
    - gpg --batch --yes --import-ownertrust <(echo "$MAVEN_GPG_OWNERTRUST")
    - gpg --armor --batch --yes --import --allow-secret-key-import <(echo "$MAVEN_GPG_KEY")
    - mvn -B -s .m2/settings.xml deploy -DskipTests -DskipITs
  only:
    - master
